import React, { useState, useMemo } from 'react';
import { Link } from 'react-router-dom';

export default function TermsAndConditions() {
  const [searchQuery, setSearchQuery] = useState('');
  const [activeCategory, setActiveCategory] = useState('All');
  const [activeSection, setActiveSection] = useState('section-1');

  const CATEGORIES = [
    { label: 'All', value: 'All' },
    { label: 'AI Advisory', value: 'AI' },
    { label: 'Mandi Prices', value: 'Mandi' },
    { label: 'Refunds & Billing', value: 'Refund' },
    { label: 'Grievance Officer', value: 'Grievance' },
    { label: 'Liability & Law', value: 'Liability' }
  ];

  const sections = [
    {
      id: 'section-1',
      number: '01',
      category: 'Legal Acceptance',
      title: 'Introduction & Legal Acceptance',
      tldr: 'By using KisanMitra (mobile app, website, or advisory APIs), you enter into a legally binding agreement with SHAMIIT LLP. If you do not agree, please discontinue using the platform.',
      content: (
        <>
          <p className="mb-4 text-gray-700 leading-relaxed">
            Welcome to <strong>KisanMitra</strong> (“Platform”, “Application”, “we”, “our”, or “us”). KisanMitra is proudly engineered, owned, and operated by <strong>SHAMIIT LLP (Shami Innovation and Technologies LLP)</strong>, a limited liability partnership registered in India on 06 December 2022 and officially recognized as an AgriTech startup by the Department for Promotion of Industry and Internal Trade (DPIIT), Ministry of Commerce and Industry, Government of India.
          </p>
          <p className="mb-4 text-gray-700 leading-relaxed">
            These Terms and Conditions (“Terms”) constitute an electronic record within the meaning of the Information Technology Act, 2000 and the rules framed thereunder, as well as the Digital Personal Data Protection Act, 2023 (DPDP). This document is generated by a computer system and does not require physical or digital signatures.
          </p>
          <p className="text-gray-700 leading-relaxed">
            By downloading our application, creating an account, browsing kisanmitra.com, or utilizing any of our artificial intelligence-assisted farming advisories, you acknowledge that you have read, understood, and agreed to be bound by these Terms and our integrated Privacy Policy.
          </p>
        </>
      )
    },
    {
      id: 'section-2',
      number: '02',
      category: 'Platform Scope',
      title: 'Platform Scope & User Eligibility',
      tldr: 'KisanMitra is crafted specifically for Indian farmers, agronomists, and agri-enterprises. Users must be at least 18 years of age or access the service under guardian supervision.',
      content: (
        <>
          <p className="mb-4 text-gray-700 leading-relaxed">
            KisanMitra delivers precision agriculture tools and insights designed specifically for Indian farming contexts:
          </p>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mb-5">
            <div className="p-4 rounded-2xl bg-gray-50 border border-gray-200/80 flex items-start gap-3">
              <span className="w-2 h-2 rounded-full bg-[#2C8C44] mt-2 shrink-0"></span>
              <span className="text-gray-800 text-sm sm:text-base">AI crop disease diagnosis and pest identification via camera photo uploads.</span>
            </div>
            <div className="p-4 rounded-2xl bg-gray-50 border border-gray-200/80 flex items-start gap-3">
              <span className="w-2 h-2 rounded-full bg-[#2C8C44] mt-2 shrink-0"></span>
              <span className="text-gray-800 text-sm sm:text-base">Hyper-local agro-meteorological advisories and 7-day rainfall/temperature forecasts.</span>
            </div>
            <div className="p-4 rounded-2xl bg-gray-50 border border-gray-200/80 flex items-start gap-3">
              <span className="w-2 h-2 rounded-full bg-[#2C8C44] mt-2 shrink-0"></span>
              <span className="text-gray-800 text-sm sm:text-base">Market price (Mandi Bhav) insights aggregated across regional APMC yards.</span>
            </div>
            <div className="p-4 rounded-2xl bg-gray-50 border border-gray-200/80 flex items-start gap-3">
              <span className="w-2 h-2 rounded-full bg-[#2C8C44] mt-2 shrink-0"></span>
              <span className="text-gray-800 text-sm sm:text-base">Central and state government agricultural subsidy and welfare scheme discovery.</span>
            </div>
          </div>
          <p className="text-gray-700 leading-relaxed">
            You represent that you are at least 18 years of age and fully competent to enter into these Terms under the Indian Contract Act, 1872. If accessing on behalf of a Farmer Producer Organization (FPO), cooperative society, or agribusiness entity, you affirm that you have full legal authority to bind that entity.
          </p>
        </>
      )
    },
    {
      id: 'section-3',
      number: '03',
      category: 'AI Advisory',
      title: 'AI Crop Advisory & Agricultural Disclaimer',
      tldr: 'CRITICAL NOTICE: AI recommendations provide advanced decision support, but they do not replace certified agricultural extension officers or laboratory soil tests. Environmental factors remain the farmer’s responsibility.',
      highlight: true,
      content: (
        <>
          <div className="p-6 sm:p-7 rounded-2xl bg-amber-50/90 border-2 border-amber-300 text-amber-950 text-base mb-6 shadow-xs">
            <div className="font-bold flex items-center gap-3 mb-2 text-lg sm:text-xl text-amber-900">
              <svg className="w-6 h-6 text-amber-700 shrink-0" fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
              </svg>
              Crucial Notice on Agricultural Advisory & Weather Analytics
            </div>
            KisanMitra utilizes state-of-the-art computer vision models, satellite telemetry, and agricultural algorithms. While we continually strive for diagnostic accuracy, agricultural outcomes depend on variable micro-climates, soil chemistry, seed lineage, and biological factors beyond digital predictability.
          </div>
          <p className="mb-4 text-gray-700 leading-relaxed">
            <strong>Decision-Support Tool Only:</strong> All crop advisories, spray dosages, disease identifications, and irrigation schedules provided by KisanMitra are intended strictly as supplementary decision-support recommendations. They do not constitute guaranteed yields or insurance against crop failure.
          </p>
          <p className="mb-4 text-gray-700 leading-relaxed">
            <strong>Mandatory Independent Verification:</strong> Before applying chemical fungicides, heavy pesticides, or making major economic investments, farmers are strongly encouraged to cross-verify severe crop distress with their local Krishi Vigyan Kendra (KVK), block agriculture officer, or a certified plant pathologist.
          </p>
          <p className="text-gray-700 leading-relaxed">
            SHAMIIT LLP disclaims all legal and financial liability for crop damages, reduced yield, or plant toxicity resulting from pesticide misapplication, unseasonal weather anomalies, drought, or floods.
          </p>
        </>
      )
    },
    {
      id: 'section-4',
      number: '04',
      category: 'Data & IP',
      title: 'User Accounts, Image Uploads & Intellectual Property',
      tldr: 'You retain full ownership of your photographs. By submitting leaf/crop photos for analysis, you grant us permission to process them to diagnose diseases and train diagnostic models.',
      content: (
        <>
          <p className="mb-4 text-gray-700 leading-relaxed">
            <strong>Account Security:</strong> You are responsible for maintaining the confidentiality of your mobile number verification codes (OTP) and login credentials. You agree to notify SHAMIIT LLP immediately in the event of any unauthorized use of your account.
          </p>
          <p className="mb-4 text-gray-700 leading-relaxed">
            <strong>Crop Photo Submissions:</strong> When you upload photographs of crops, leaves, or fields for automated disease diagnosis, you retain intellectual property ownership of your media. However, you grant KisanMitra a perpetual, royalty-free, worldwide license to process, resize, and use anonymized image data exclusively for the purpose of improving diagnostic neural networks and agronomic algorithms.
          </p>
          <p className="text-gray-700 leading-relaxed">
            <strong>Platform Proprietary Rights:</strong> All KisanMitra trademarks, brand logos, user interface designs, software architectures, algorithms, and editorial guides are the proprietary intellectual property of SHAMIIT LLP and are fully protected under Indian copyright and trademark law.
          </p>
        </>
      )
    },
    {
      id: 'section-5',
      number: '05',
      category: 'Mandi Prices',
      title: 'Market Prices (Mandi Bhav) & Third-Party Information',
      tldr: 'Mandi prices and government scheme details are compiled from public feeds (Agmarknet, e-NAM) for educational awareness. Always confirm active rates with your local APMC yard before selling.',
      content: (
        <>
          <p className="mb-4 text-gray-700 leading-relaxed">
            <strong>Spot Price Accuracy:</strong> KisanMitra aggregates spot commodity rates and trends from Agricultural Produce Market Committees (APMCs), national commodity databases, and local market reports. Because market auctions fluctuate by the hour according to arrivals and produce quality grades, rates shown are indicative benchmark points only.
          </p>
          <p className="mb-4 text-gray-700 leading-relaxed">
            <strong>No Commercial Brokerage:</strong> KisanMitra does not act as a commission agent, broker, or financial guarantor for produce sales between farmers and third-party buyers, unless specifically executed under an authorized corporate procurement agreement.
          </p>
          <p className="text-gray-700 leading-relaxed">
            <strong>Government Schemes:</strong> Information relating to PM-KISAN, PMFBY crop insurance, or state-specific subsidies is compiled for farmer awareness. Final application approval and disbursal remain under the sole jurisdiction of the respective government authorities.
          </p>
        </>
      )
    },
    {
      id: 'section-6',
      number: '06',
      category: 'Refund & Billing',
      title: 'Subscription Tiers, Billing & Refund Principles',
      tldr: 'Essential services remain accessible free of charge. Premium feature packages are transparently priced, with refund requests evaluated under our customer assurance policy.',
      content: (
        <>
          <p className="mb-4 text-gray-700 leading-relaxed">
            <strong>Free vs. Premium Tiers:</strong> KisanMitra provides essential agricultural advisory tools free of cost to support Indian farmers. Advanced features—such as deep-learning disease analytics, unlimited history logs, and priority agronomy consultations—may be offered under paid tier plans.
          </p>
          <p className="mb-4 text-gray-700 leading-relaxed">
            <strong>Secure Transactions:</strong> All financial transactions are processed securely through RBI-authorized payment aggregators and UPI networks. KisanMitra does not store sensitive payment credentials such as debit/credit card CVVs or net-banking passwords.
          </p>
          <p className="text-gray-700 leading-relaxed">
            <strong>Cancellations & Refunds:</strong> Any billing discrepancies, accidental duplicate payments, or cancellation requests are handled in accordance with our <Link to="/refund-policy" className="text-[#2C8C44] font-bold hover:underline">Refund Policy</Link> within standard statutory timelines.
          </p>
        </>
      )
    },
    {
      id: 'section-7',
      number: '07',
      category: 'Fair Use',
      title: 'Prohibited Activities & Fair Usage',
      tldr: 'You agree not to reverse-engineer our AI models, scrape automated data, upload malicious files, or misuse the farmer community.',
      content: (
        <>
          <p className="mb-4 text-gray-700 leading-relaxed">When accessing KisanMitra, you strictly agree not to:</p>
          <ul className="list-disc pl-6 mb-4 space-y-2.5 text-gray-700">
            <li>Decompile, disassemble, reverse engineer, or extract proprietary code or AI model weights from KisanMitra.</li>
            <li>Deploy automated crawlers, scrapers, or bot scripts to harvest mandi rates or user profile data.</li>
            <li>Submit fraudulent, counterfeit, or misleading farm documents or irrelevant/offensive photographs.</li>
            <li>Engage in abusive, defamatory, or threatening behavior toward customer support staff or other community members.</li>
            <li>Bypass or tamper with security tokens, firewalls, rate limits, or user authentication mechanisms.</li>
          </ul>
          <p className="text-gray-700 leading-relaxed">
            Any violation of these fair usage terms may result in immediate suspension or permanent termination of your KisanMitra account without refund.
          </p>
        </>
      )
    },
    {
      id: 'section-8',
      number: '08',
      category: 'Liability',
      title: 'Limitation of Liability & Indemnification',
      tldr: 'Under no circumstances will SHAMIIT LLP be liable for indirect crop losses, climate events, or network outages beyond reasonable control.',
      content: (
        <>
          <p className="mb-4 text-gray-700 leading-relaxed">
            To the maximum extent permitted by applicable Indian law, SHAMIIT LLP, its designated partners, engineers, agronomic researchers, and affiliates shall not be liable for any indirect, incidental, punitive, or consequential damages, including loss of crop yield, harvest revenue, soil fertility, or business opportunity.
          </p>
          <p className="mb-4 text-gray-700 leading-relaxed">
            In all events, our total aggregate liability arising out of or related to your use of KisanMitra shall not exceed the total fees actually paid by you to KisanMitra in the preceding three (3) months, or INR 1,000 (Indian Rupees One Thousand), whichever is less.
          </p>
          <p className="text-gray-700 leading-relaxed">
            You agree to defend, indemnify, and hold harmless SHAMIIT LLP and its partners from any third-party claims, liabilities, or legal costs arising from your violation of these Terms or misuse of advice provided through the platform.
          </p>
        </>
      )
    },
    {
      id: 'section-9',
      number: '09',
      category: 'Grievance',
      title: 'Grievance Redressal Mechanism & Officer',
      tldr: 'In compliance with IT Rules 2021, our designated Grievance Officer acknowledges complaints within 24 hours and resolves them within 15 days.',
      content: (
        <>
          <p className="mb-4 text-gray-700 leading-relaxed">
            In accordance with the Information Technology Act, 2000 and the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021, the contact details of our Grievance Redressal Officer are published below:
          </p>
          <div className="p-6 sm:p-7 rounded-2xl bg-gray-50 border border-gray-200 text-sm sm:text-base space-y-2.5 leading-relaxed">
            <p><strong>Designation:</strong> Grievance Redressal Officer, KisanMitra</p>
            <p><strong>Entity:</strong> SHAMIIT LLP (Shami Innovation and Technologies LLP)</p>
            <p><strong>Physical Address:</strong> Dayanatpur Jewar, Greater Noida, Gautam Buddha Nagar, Uttar Pradesh - 203135, India</p>
            <p><strong>Email:</strong> <a href="mailto:support@kisanmitra.com" className="text-[#2C8C44] hover:underline font-semibold">support@kisanmitra.com</a> (Attn: Grievance Officer)</p>
            <p><strong>Acknowledgement:</strong> Within 24 hours &nbsp;|&nbsp; <strong>Resolution Window:</strong> Within 15 business days</p>
          </div>
        </>
      )
    },
    {
      id: 'section-10',
      number: '10',
      category: 'Jurisdiction',
      title: 'Governing Law, Jurisdiction & Dispute Resolution',
      tldr: 'All disputes are subject to the laws of India and the exclusive jurisdiction of the courts in Gautam Buddha Nagar / Greater Noida, Uttar Pradesh.',
      content: (
        <>
          <p className="mb-4 text-gray-700 leading-relaxed">
            These Terms and any contractual or non-contractual disputes arising out of your relationship with KisanMitra shall be governed by and construed in accordance with the laws of the Republic of India.
          </p>
          <p className="mb-4 text-gray-700 leading-relaxed">
            <strong>Amicable Negotiation:</strong> In the event of any dispute or controversy, both parties agree to first attempt to resolve the issue through good-faith consultation for a period of at least thirty (30) calendar days from written notification.
          </p>
          <p className="text-gray-700 leading-relaxed">
            <strong>Exclusive Jurisdiction:</strong> If unresolved, any formal legal proceedings shall be subject to the exclusive jurisdiction of the competent civil courts situated in <strong>Gautam Buddha Nagar / Greater Noida, Uttar Pradesh, India</strong>.
          </p>
        </>
      )
    },
    {
      id: 'section-11',
      number: '11',
      category: 'Support',
      title: 'Modifications & Multilingual Support',
      tldr: 'We may update these terms periodically to reflect new regulations or features. Continued use confirms acceptance. Reach out to our support desk anytime.',
      content: (
        <>
          <p className="mb-4 text-gray-700 leading-relaxed">
            SHAMIIT LLP reserves the right to amend or update these Terms at any time to reflect technological upgrades, regulatory shifts under the Digital Personal Data Protection Act, or service enhancements. The revised terms will always display the latest “Effective Date” at the top of this document.
          </p>
          <p className="mb-5 text-gray-700 leading-relaxed">
            If you have questions, feedback, or require assistance in your preferred regional language (Hindi, Marathi, English), please connect with our team:
          </p>
          <div className="flex flex-wrap gap-4 text-sm sm:text-base font-semibold">
            <a
              href="mailto:support@kisanmitra.com"
              className="inline-flex items-center gap-2.5 px-6 py-3.5 bg-emerald-50 text-[#123C26] rounded-2xl border border-[#A6CDB3]/60 hover:bg-emerald-100 transition-colors shadow-xs"
            >
              <svg className="w-5 h-5 text-[#2C8C44]" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" d="M21.75 6.75v10.5a2.25 2.25 0 0 1-2.25 2.25h-15a2.25 2.25 0 0 1-2.25-2.25V6.75m19.5 0A2.25 2.25 0 0 0 19.5 4.5h-15a2.25 2.25 0 0 0-2.25 2.25m19.5 0v.243a2.25 2.25 0 0 1-1.07 1.916l-7.5 4.615a2.25 2.25 0 0 1-2.36 0L3.32 8.91a2.25 2.25 0 0 1-1.07-1.916V6.75" />
              </svg>
              support@kisanmitra.com
            </a>
            <a
              href="tel:+919548450539"
              className="inline-flex items-center gap-2.5 px-6 py-3.5 bg-emerald-50 text-[#123C26] rounded-2xl border border-[#A6CDB3]/60 hover:bg-emerald-100 transition-colors shadow-xs"
            >
              <svg className="w-5 h-5 text-[#2C8C44]" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" d="M2.25 6.75c0 8.284 6.716 15 15 15h2.25a2.25 2.25 0 0 0 2.25-2.25v-1.372c0-.516-.351-.966-.852-1.091l-4.423-1.106c-.44-.11-.902.055-1.173.417l-.97 1.293c-2.896-1.596-5.14-3.84-6.736-6.736l1.293-.97c.363-.271.527-.734.417-1.173L6.963 3.102a1.125 1.125 0 0 0-1.091-.852H4.5A2.25 2.25 0 0 0 2.25 4.5v2.25Z" />
              </svg>
              +91 95484 50539
            </a>
          </div>
        </>
      )
    }
  ];

  // Filter sections by search query and category
  const filteredSections = useMemo(() => {
    let result = sections;
    if (activeCategory !== 'All') {
      const catLower = activeCategory.toLowerCase();
      result = result.filter(
        (sec) =>
          sec.title.toLowerCase().includes(catLower) ||
          sec.category.toLowerCase().includes(catLower) ||
          sec.tldr.toLowerCase().includes(catLower)
      );
    }
    if (searchQuery.trim()) {
      const query = searchQuery.toLowerCase();
      result = result.filter(
        (sec) =>
          sec.title.toLowerCase().includes(query) ||
          sec.tldr.toLowerCase().includes(query) ||
          sec.category.toLowerCase().includes(query)
      );
    }
    return result;
  }, [searchQuery, activeCategory, sections]);

  const scrollToSection = (id) => {
    setActiveSection(id);
    const element = document.getElementById(id);
    if (element) {
      const yOffset = -90;
      const y = element.getBoundingClientRect().top + window.pageYOffset + yOffset;
      window.scrollTo({ top: y, behavior: 'smooth' });
    }
  };

  return (
    <div className="w-full bg-[#FAFCFA] min-h-screen text-gray-800">
      
      {/* Header Banner - Full Width Fluid Container */}
      <header className="bg-gradient-to-b from-[#0A2213] via-[#0E2F1B] to-[#123C26] text-white pt-16 pb-20 px-6 sm:px-10 md:px-12 lg:px-16 relative overflow-hidden w-full">
        {/* Ambient background glows */}
        <div className="absolute -top-32 -left-32 w-[500px] h-[500px] bg-[#80D939]/15 rounded-full filter blur-3xl pointer-events-none"></div>
        <div className="absolute -bottom-32 -right-32 w-[500px] h-[500px] bg-[#2C8C44]/20 rounded-full filter blur-3xl pointer-events-none"></div>

        <div className="w-full max-w-[96rem] mx-auto relative z-10">
          
          {/* Breadcrumb & Badges */}
          <div className="flex flex-wrap items-center gap-2.5 mb-5 text-sm">
            <Link to="/" className="text-gray-300 hover:text-white transition-colors">
              Home
            </Link>
            {/* <span className="text-gray-500">/</span>
            <span className="text-[#80D939] font-semibold">Legal & Governance</span> */}
            <span className="text-gray-500">/</span>
            <span className="text-gray-200">Terms & Conditions</span>
          </div>

          <div className="flex flex-wrap items-center gap-3 mb-6">
            <span className="bg-[#1a4a2e] text-[#B0D939] px-4 py-1.5 rounded-full text-xs sm:text-sm font-semibold border border-[#2a6843] shadow-xs">
              DPIIT Recognized AgriTech Startup
            </span>
            <span className="bg-white/10 text-gray-200 px-4 py-1.5 rounded-full text-xs sm:text-sm font-medium">
              Effective Date: March 01, 2026
            </span>
            <span className="bg-white/10 text-gray-200 px-4 py-1.5 rounded-full text-xs sm:text-sm font-medium">
              Version 2.4
            </span>
          </div>

          <h1 className="text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-black tracking-tight mb-5 text-white leading-[1.1]">
            Terms & Conditions of Service
          </h1>

          <p className="text-gray-200 text-base sm:text-lg md:text-xl lg:text-2xl max-w-5xl leading-relaxed mb-8">
            Please review these terms carefully. They define your legal rights, obligations, and the agricultural advisory disclaimers governing your use of KisanMitra, an innovation by SHAMIIT LLP.
          </p>

          {/* Quick Actions Bar */}
          <div className="flex flex-wrap items-center gap-4 text-sm sm:text-base">
            <button
              onClick={() => window.print()}
              className="inline-flex items-center gap-2.5 px-6 py-3 bg-white/10 hover:bg-white/20 text-white font-semibold rounded-2xl border border-white/20 transition-all cursor-pointer shadow-xs"
            >
              <svg className="w-5 h-5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" d="M6.72 13.829c-.24-1.076-.64-2.074-1.18-2.964m11.92 2.964c.24-1.076.64-2.074 1.18-2.964m-14.28 0a9 9 0 1114.28 0M6 18h12a2 2 0 002-2v-4a2 2 0 00-2-2H6a2 2 0 00-2 2v4a2 2 0 002 2zm2-10h8V4H8v4z" />
              </svg>
              Print / Save PDF
            </button>
            <Link
              to="/contact"
              className="inline-flex items-center gap-2 px-6 py-3 bg-[#B0D939] hover:bg-[#9cc233] text-[#123C26] font-bold rounded-2xl transition-all shadow-xs"
            >
              Have Questions? Contact Us
            </Link>
          </div>

        </div>
      </header>

      {/* Main Body - Generous Full-Width Fluid Canvas */}
      <main className="w-full max-w-[96rem] mx-auto px-4 sm:px-6 md:px-10 lg:px-12 xl:px-16 py-10 md:py-16">
        
        {/* Assurance Strip Covering Screen Width */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 md:gap-5 mb-10 w-full">
          <div className="p-5 rounded-2xl bg-white border border-gray-200/80 shadow-xs flex items-center gap-4">
            <div className="w-12 h-12 rounded-xl bg-[#EAF7ED] flex items-center justify-center text-[#2C8C44] shrink-0 font-bold text-xl">
              🇮🇳
            </div>
            <div>
              <h4 className="font-bold text-[#123C26] text-sm sm:text-base">DPIIT Recognized</h4>
              <p className="text-xs sm:text-sm text-gray-500">Startup India Certified AgriTech</p>
            </div>
          </div>
          <div className="p-5 rounded-2xl bg-white border border-gray-200/80 shadow-xs flex items-center gap-4">
            <div className="w-12 h-12 rounded-xl bg-[#EAF7ED] flex items-center justify-center text-[#2C8C44] shrink-0 font-bold text-xl">
              ⚖️
            </div>
            <div>
              <h4 className="font-bold text-[#123C26] text-sm sm:text-base">Indian IT Act 2000</h4>
              <p className="text-xs sm:text-sm text-gray-500">Compliant with DPDP Act 2023</p>
            </div>
          </div>
          <div className="p-5 rounded-2xl bg-white border border-gray-200/80 shadow-xs flex items-center gap-4">
            <div className="w-12 h-12 rounded-xl bg-[#EAF7ED] flex items-center justify-center text-[#2C8C44] shrink-0 font-bold text-xl">
              🌾
            </div>
            <div>
              <h4 className="font-bold text-[#123C26] text-sm sm:text-base">Decision Support</h4>
              <p className="text-xs sm:text-sm text-gray-500">Supplementary Advisory Guidance</p>
            </div>
          </div>
          <div className="p-5 rounded-2xl bg-white border border-gray-200/80 shadow-xs flex items-center gap-4">
            <div className="w-12 h-12 rounded-xl bg-[#EAF7ED] flex items-center justify-center text-[#2C8C44] shrink-0 font-bold text-xl">
              🛡️
            </div>
            <div>
              <h4 className="font-bold text-[#123C26] text-sm sm:text-base">Grievance Redressal</h4>
              <p className="text-xs sm:text-sm text-gray-500">15-Day Statutory Resolution Window</p>
            </div>
          </div>
        </div>

        {/* Search & Quick Filter Category Pills */}
        <div className="mb-10 w-full bg-white rounded-3xl p-5 md:p-6 border border-gray-200/90 shadow-sm flex flex-col lg:flex-row gap-5 items-center justify-between">
          <div className="flex items-center gap-3 w-full lg:w-[45%] bg-gray-50 px-4 py-3 rounded-2xl border border-gray-200 focus-within:ring-2 focus-within:ring-[#2C8C44]/30 focus-within:border-[#2C8C44] transition-all">
            <svg className="w-6 h-6 text-gray-400 shrink-0" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
            </svg>
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search terms (e.g. AI advice, refund, crop damage, mandi, liability)..."
              className="w-full bg-transparent text-sm sm:text-base outline-none text-gray-800 placeholder-gray-400"
            />
            {searchQuery && (
              <button
                onClick={() => setSearchQuery('')}
                className="text-xs text-gray-500 hover:text-gray-800 px-2 py-1 rounded bg-gray-200"
              >
                Clear
              </button>
            )}
          </div>

          {/* Filter Pills */}
          <div className="flex flex-wrap items-center gap-2 w-full lg:w-auto">
            {CATEGORIES.map((cat) => (
              <button
                key={cat.value}
                onClick={() => setActiveCategory(cat.value)}
                className={`px-4 py-2 rounded-xl text-xs sm:text-sm font-semibold transition-all cursor-pointer ${
                  activeCategory === cat.value
                    ? 'bg-[#123C26] text-white shadow-xs'
                    : 'bg-gray-100 text-gray-600 hover:bg-gray-200 hover:text-gray-900'
                }`}
              >
                {cat.label}
              </button>
            ))}
          </div>
        </div>

        {/* Spacious 2-Column Responsive Layout: Compact Sidebar + Expansive Content */}
        <div className="flex flex-col lg:flex-row gap-8 lg:gap-10 items-start w-full">
          
          {/* Left Column: Table of Contents (Sticky on Desktop, Compact 280px-320px) */}
          <aside className="lg:w-72 xl:w-80 shrink-0 sticky top-24 hidden lg:block">
            <div className="bg-white rounded-3xl border border-gray-200/90 p-6 shadow-xs">
              <h3 className="font-bold text-gray-900 text-sm uppercase tracking-wider mb-4 pb-3 border-b border-gray-100 flex items-center justify-between">
                <span>Table of Contents</span>
                <span className="text-xs text-gray-500 font-bold bg-[#EAF7ED] text-[#2C8C44] px-2.5 py-0.5 rounded-full">{sections.length} Clauses</span>
              </h3>
              <nav className="flex flex-col space-y-1 text-sm max-h-[65vh] overflow-y-auto pr-1">
                {sections.map((sec) => (
                  <button
                    key={sec.id}
                    onClick={() => scrollToSection(sec.id)}
                    className={`text-left px-3.5 py-2.5 rounded-xl transition-all flex items-start gap-2.5 cursor-pointer ${
                      activeSection === sec.id
                        ? 'bg-[#EAF7ED] text-[#123C26] font-bold border-l-4 border-[#2C8C44]'
                        : 'text-gray-600 hover:bg-gray-50 hover:text-gray-900'
                    }`}
                  >
                    <span className="text-xs text-gray-400 font-mono shrink-0 mt-0.5">{sec.number}</span>
                    <span className="line-clamp-1 leading-snug">{sec.title}</span>
                  </button>
                ))}
              </nav>

              <div className="mt-6 pt-4 border-t border-gray-100 text-xs text-gray-500 flex flex-col gap-2 leading-relaxed">
                <p>
                  <strong>Entity:</strong> SHAMIIT LLP<br />
                  <strong>Reg Date:</strong> 06 Dec 2022<br />
                  <strong>Jurisdiction:</strong> Greater Noida, UP
                </p>
                <Link to="/refund-policy" className="text-[#2C8C44] hover:underline font-bold mt-1 text-sm inline-flex items-center gap-1">
                  View Refund Policy →
                </Link>
              </div>
            </div>
          </aside>

          {/* Right Column: Clauses Content (Expansive, filling the entire laptop screen width) */}
          <div className="flex-1 min-w-0 w-full flex flex-col space-y-8 md:space-y-10">
            
            {filteredSections.length === 0 ? (
              <div className="bg-white p-12 rounded-3xl border border-gray-200 text-center text-gray-500 w-full">
                <p className="font-bold text-xl text-gray-800 mb-2">No matching clauses found</p>
                <p className="text-base mb-4">Try clearing your search query or selecting "All" categories.</p>
                <button
                  onClick={() => {
                    setSearchQuery('');
                    setActiveCategory('All');
                  }}
                  className="px-6 py-2.5 bg-[#123C26] text-white rounded-xl text-sm font-bold hover:bg-[#1b5034] transition-colors"
                >
                  Reset Filter
                </button>
              </div>
            ) : (
              filteredSections.map((sec) => (
                <article
                  key={sec.id}
                  id={sec.id}
                  className={`bg-white rounded-3xl border p-8 sm:p-10 md:p-12 shadow-xs transition-all w-full ${
                    sec.highlight
                      ? 'border-[#80D939]/80 shadow-[0_8px_30px_rgba(84,180,53,0.1)] ring-1 ring-[#80D939]/30'
                      : 'border-gray-200/90 hover:border-gray-300'
                  }`}
                >
                  {/* Clause Header & Category Pill */}
                  <div className="flex flex-wrap items-center justify-between gap-3 mb-4">
                    <div className="flex items-center gap-3.5">
                      <span className="w-11 h-11 rounded-xl bg-[#EAF7ED] text-[#2C8C44] font-mono text-base font-extrabold flex items-center justify-center shrink-0">
                        {sec.number}
                      </span>
                      <h2 className="text-2xl sm:text-3xl md:text-4xl font-extrabold text-gray-900 leading-tight">
                        {sec.title}
                      </h2>
                    </div>
                    <span className="text-xs font-bold uppercase tracking-wider px-3.5 py-1.5 rounded-full bg-gray-100 text-gray-600 border border-gray-200">
                      {sec.category}
                    </span>
                  </div>

                  {/* TL;DR Farmer-Friendly Summary Box */}
                  <div className="bg-[#F4F9F5] border-l-4 border-[#2C8C44] p-5 rounded-r-2xl text-sm sm:text-base text-gray-700 leading-relaxed mb-6">
                    <span className="font-bold text-[#123C26] uppercase tracking-wider text-xs block mb-1">
                      Plain English Farmer Summary
                    </span>
                    {sec.tldr}
                  </div>

                  {/* Full Legal Text */}
                  <div className="text-gray-700 text-base sm:text-lg leading-relaxed">
                    {sec.content}
                  </div>
                </article>
              ))
            )}

            {/* Bottom Contact Callout */}
            <div className="p-8 sm:p-10 rounded-3xl bg-[#EAF7ED] border border-[#A6CDB3]/60 flex flex-col md:flex-row items-center justify-between gap-6 shadow-xs w-full">
              <div>
                <h4 className="font-bold text-[#123C26] text-xl sm:text-2xl mb-1.5">
                  Need Legal or Agricultural Clarification?
                </h4>
                <p className="text-sm sm:text-base text-gray-600 leading-relaxed max-w-2xl">
                  Our agronomic team and legal officers are available to assist farmers in Hindi, English, and regional Indian languages.
                </p>
              </div>
              <Link
                to="/contact"
                className="px-8 py-4 bg-[#123C26] text-white rounded-2xl text-base font-bold hover:bg-[#1b5034] transition-colors whitespace-nowrap shadow-xs hover:shadow-md cursor-pointer"
              >
                Contact Support Team
              </Link>
            </div>

          </div>

        </div>

      </main>

    </div>
  );
}
